version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    restart: on-failure
    env_file:
      - .env
    networks:
      custom-network:
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  custom-network:
    driver: bridge
